title: Thanh Hải & Phương Ngân
email: hai@haiphan.design
description: >-
    Just another website by Hải
baseurl: ''
url: ''

collections:
    albums:
        output: true
        title: Albums
        permalink: /album/:slug

plugins:
    - jekyll-feed
    - jekyll-seo-tag

sass:
    style: compressed
